import type { OfficialIndexResult } from '../../official-index/contracts'
import { TrustBadge } from '../decision-brief/TrustBadge'

export function OfficialIndexPanel({ result }: { result: OfficialIndexResult }) {
  if (result.kind === 'UNSUPPORTED_POINT') return <section className="official-section" aria-labelledby="official-heading"><div className="section-title-row"><div><p className="section-kicker">OFFICIAL INDEX</p><h3 id="official-heading">어종별 공식 바다낚시지수</h3></div></div><div className="inline-state"><strong>{result.reason}</strong><p>지원 포인트가 아니므로 어종 결과를 생성하지 않습니다.</p></div></section>
  if (result.kind === 'COLLECTION_FAILED') return <section className="official-section" aria-labelledby="official-heading"><div className="section-title-row"><div><p className="section-kicker">OFFICIAL INDEX</p><h3 id="official-heading">어종별 공식 바다낚시지수</h3></div><TrustBadge status="COLLECTION_FAILED" /></div><div className="inline-state"><strong>공식 데이터 수집 실패</strong><p>{result.reason}</p></div></section>
  return <section className="official-section" aria-labelledby="official-heading">
    <div className="section-title-row"><div><p className="section-kicker">OFFICIAL INDEX · {result.demo ? 'DEMO' : 'LIVE'}</p><h3 id="official-heading">어종별 공식 바다낚시지수</h3><p>{result.point.placeName} 기준 · {result.demo ? '실제 API 스키마 기반 시연 데이터' : '국립해양조사원 제공 예보'}</p></div></div>
    {result.species.length > 0 && <div className="species-summary" aria-label="오늘 확인할 어종"><h4>오늘 확인할 어종</h4><ul>{result.species.map(item => <li key={item.speciesId}>{item.speciesName} · 공식 지수 {item.officialGrade}</li>)}</ul></div>}
    <div className="species-grid">{result.species.map((item) => <article className="species-card" key={item.speciesId}><div className="species-top"><div><span className="data-label">대상 어종</span><h4>{item.speciesName}</h4></div><TrustBadge status={item.trustStatus} /></div><dl><div><dt>공식 등급</dt><dd>{item.officialGrade}</dd></div><div><dt>공식 점수</dt><dd>{item.officialScore ?? '제공 없음'}</dd></div><div><dt>기준시각</dt><dd className="mono">{item.evaluatedAt}</dd></div></dl><details><summary>근거 보기 · {item.speciesName}</summary><p>{item.source}</p><p>{result.point.placeName} · {item.evaluatedAt}</p><p>신뢰상태: {item.trustStatus}</p></details></article>)}</div>
    <div className="environment-block"><h4>현재 환경</h4><div className="environment-grid">{result.environment.observations.map((item, index) => <div className="environment-item" key={`${item.metricType}:${index}`}><span>{item.label}</span><strong>{item.value} <small>{item.unit}</small></strong><TrustBadge status={item.trustStatus} /><details><summary>근거 보기 · {item.label}</summary><p>{item.source}</p><p>{item.forecastAt} · {result.point.placeName}</p><p>출처 기준시각: {item.sourceTimestamp}</p></details></div>)}</div></div>
    <p className="official-note">공식 등급은 제공기관의 낚시여건 지수이며, 신뢰상태는 데이터의 수집·시각 근거 상태입니다. 사용자의 출조 결정이나 안전·허용 판단을 대신하지 않습니다.</p>
  </section>
}
